nasa_neows:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: nasa-neows
      dataset: your-dbt-dataset
      keyfile: /opt/airflow/.google/nasa-neows-c12d19292fad.json
      location: your-region
      threads: 4
